CDK migration to multi-module Terraform (#146)
* PLAT-7142: Update CDK to TF migration for multi-module structure

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -5,22 +5,19 @@ name: Run tests / create artifacts
 
 on:
   push:
-    branches: [ master ]
+    branches: [master]
   pull_request:
     types: [opened, synchronize, reopened, labeled, ready_for_review]
-    branches: [ master ]
+    branches: [master]
 
 jobs:
   test-build-deploy:
     permissions:
       id-token: write
       contents: read
-
     runs-on: ubuntu-latest
-
     env:
       AWS_REGION: us-west-2
-
     defaults:
       run:
         working-directory: ./cdk
@@ -35,6 +32,9 @@ jobs:
       uses: actions/setup-node@v2
       with:
         node-version: 18
+    - uses: hashicorp/setup-terraform@v2
+      with:
+        terraform_version: 1.5.6
     - name: Install dependencies
       run: |
         pip install -r requirements.txt
@@ -59,10 +59,10 @@ jobs:
     - name: Coverage report
       run: |
         coverage report
-
     - name: Authenticate with AWS
-      uses: aws-actions/configure-aws-credentials@v2
+      uses: aws-actions/configure-aws-credentials@v3
       with:
+        unset-current-credentials: true
         role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
         aws-region: ${{ env.AWS_REGION }}
     - name: Create/lint default config
@@ -120,8 +120,9 @@ jobs:
         $(jq -r ".[].ekskubeconfigcmd" outputs.json) --kubeconfig ./kubeconfig
 
     - name: Authenticate with AWS
-      uses: aws-actions/configure-aws-credentials@v2
+      uses: aws-actions/configure-aws-credentials@v3
       with:
+        unset-current-credentials: true
         role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
         aws-region: ${{ env.AWS_REGION }}
     - name: Collect diagnostic data
@@ -154,37 +155,92 @@ jobs:
         terraform init
         terraform plan -out=terraform.plan
         terraform apply -auto-approve terraform.plan
+    - name: Install hcledit
+      run: |
+        hcledit_version="0.2.9"
+        hcledit_artifact=hcledit_${hcledit_version}_linux_amd64.tar.gz
+        curl -fsSL -o "${hcledit_artifact}" "https://github.com/minamijoyo/hcledit/releases/download/v${hcledit_version}/${hcledit_artifact}"
+        tar xvzf "${hcledit_artifact}"
+        sudo mv hcledit /usr/local/bin/ && rm "${hcledit_artifact}" && hcledit version
     - name: Setup terraform-aws-eks conversion process
       if: (contains(github.event.pull_request.labels.*.name, 'deploy-test') || github.ref == 'refs/heads/master')
       working-directory: ./convert
       run: |
         pip install -r requirements.txt
         ssh-keygen -t rsa -f dummy.pem -N ''
-        ./convert.py print-stack --stack-name $NAME --region $AWS_REGION --verbose --yaml > stack-data.yaml
-        ./convert.py create-tfvars --stack-name $NAME --region $AWS_REGION --ssh-key-path ./dummy.pem > terraform/terraform.tfvars.json
-        ./convert.py get-imports --stack-name $NAME --region $AWS_REGION > terraform/imports.sh
+
+        export STACK_NAME="$NAME"
+        export MOD_VERSION="v3.0.1"
+
+        envsubst < config.tpl | tee config.yaml
+        ./convert.py check-requirements
+        ./convert.py print-stack --verbose --yaml > stack-data.yaml
+        ./convert.py setup-tf-modules
+        ./convert.py create-tfvars --ssh-key-path ./dummy.pem
+        ./convert.py set-imports
     - name: Run terraform
       if: (contains(github.event.pull_request.labels.*.name, 'deploy-test') || github.ref == 'refs/heads/master')
-      working-directory: ./convert/terraform
+      working-directory: ./convert
       run: |
-        terraform init
-        bash imports.sh
-        terraform plan -out=terraform.plan
-        terraform show -json terraform.plan | jq '.resource_changes[] | select(.change.actions[]=="delete")' | tee terraform.plan.json
-        test -s terraform.plan.json && echo "Detected deletions, bailing..." && exit 1
-        terraform apply -auto-approve terraform.plan
+        set -euo pipefail
+
+        pushd "$NAME" >/dev/null || { echo "Error changing into $NAME." && exit 1; }
+
+        if ! source "meta.sh"; then
+          echo "There was an error sourcing meta.sh"
+          exit 1
+        fi
+
+        for component in cdk_tf infra cluster nodes; do
+          echo "Running terraform for $component"
+
+          if ! ./tf.sh "$component" 'init'; then
+            echo "Initialization for $component failed. Exiting..."
+            exit 1
+          fi
+
+          if ! ./tf.sh "$component" 'plan_out'; then
+            echo "Plan for $component failed. Exiting..."
+            exit 1
+          fi
+
+          echo "Checking plan for resource deletes.."
+
+          if ! ./tf.sh "$component" 'show_plan_json' | \
+          sed -n '/^{.*}$/p' | \
+          jq '.resource_changes[] | select(.change.actions | contains(["delete"]))' | \
+          tee "${component}-tf-deletes.plan.json"; then
+            echo "Error processing json plan for deletes inspection. Exiting..."
+            exit 1
+          fi
+
+          if [ -s "${component}-tf-deletes.plan.json" ]; then
+            echo "Detected deletions, bailing..."
+            exit 1
+          else
+            echo "No deletes found"
+          fi
+
+          if ! ./tf.sh "$component" 'apply_plan'; then
+            echo "Apply plan for $component failed. Exiting..."
+            exit 1
+          fi
+        done
+
+        popd >/dev/null || exit 1
 
     - name: Authenticate with AWS
-      uses: aws-actions/configure-aws-credentials@v2
+      uses: aws-actions/configure-aws-credentials@v3
       with:
+        unset-current-credentials: true
         role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
         aws-region: ${{ env.AWS_REGION }}
     - name: Clean and delete stack
       if: (contains(github.event.pull_request.labels.*.name, 'deploy-test') || github.ref == 'refs/heads/master')
       working-directory: ./convert
       run: |
-        ./convert.py clean-stack --stack-name $NAME --region $AWS_REGION --remove-security-group-references --delete
-        ./convert.py delete-stack --stack-name $NAME --region $AWS_REGION --delete
+        ./convert.py clean-stack --remove-security-group-references --delete
+        ./convert.py delete-stack --delete
     - name: Upload diagnostic data
       if: always() && (contains(github.event.pull_request.labels.*.name, 'deploy-test') || github.ref == 'refs/heads/master')
       uses: actions/upload-artifact@v2
@@ -194,9 +250,11 @@ jobs:
         retention-days: 14
 
     - name: Authenticate with AWS
-      uses: aws-actions/configure-aws-credentials@v2
+      uses: aws-actions/configure-aws-credentials@v3
       if: always() && (contains(github.event.pull_request.labels.*.name, 'deploy-test') || github.ref == 'refs/heads/master')
       with:
+        role-duration-seconds: 7200
+        unset-current-credentials: true
         role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
         aws-region: ${{ env.AWS_REGION }}
     - name: Delete stack w/CDK
@@ -208,9 +266,13 @@ jobs:
         cdk destroy --force
     - name: Destroy Infrastructure tf
       if: always() && (contains(github.event.pull_request.labels.*.name, 'deploy-test') || github.ref == 'refs/heads/master')
-      working-directory: ./convert/terraform
+      working-directory: ./convert
       run: |
-        terraform destroy -auto-approve
+        cd "$NAME"
+        for component in 'nodes' 'cluster' 'infra' 'cdk_tf'; do
+          echo "Running terraform for $component"
+          ./tf.sh "$component" destroy
+        done
     - name: Destroy Infrastructure cf
       if: always() && (contains(github.event.pull_request.labels.*.name, 'deploy-test') || github.ref == 'refs/heads/master')
       working-directory: ./convert/cloudformation-only
