Added debug to error, 2

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -203,11 +203,12 @@ jobs:
                 echo "Checking plan for deletes.."
 
                 echo "terraform plan at: ${BASE_TF_DIR}/${component}-terraform.plan"
+                terraform show -json "${BASE_TF_DIR}/${component}-terraform.plan" > "${BASE_TF_DIR}/${component}-changes.plan.json"
 
-                if ! terraform show -json "${BASE_TF_DIR}/${component}-terraform.plan" > "${BASE_TF_DIR}/${component}-changes.plan.json"; then
-                  echo "Terraform show command for $component failed. Exiting..."
-                  exit 1
-                fi
+                # if ! terraform show -json "${BASE_TF_DIR}/${component}-terraform.plan" > "${BASE_TF_DIR}/${component}-changes.plan.json"; then
+                #   echo "Terraform show command for $component failed. Exiting..."
+                #   exit 1
+                # fi
 
                 jq -c 'select(.change.actions | contains(["delete"]))' "${BASE_TF_DIR}/${component}-changes.plan.json" > "${component}-tf-deletes.plan.json"
                 cat "${component}-tf-deletes.plan.json"
